### ISSUE TITLE
[addon] - Post Types Reorder

### ISSUE THREAD

**Issue by MaximeCulea** [BeAPI/bea-content-sync-fusion#10]
https://fr.wordpress.org/plugins/post-types-order/

**Comment by MaximeCulea** [comment]
⚠️  The Post Types Reorder plugin doesn't check if order has change or not for a post, it always makes the update.
In our case this result into syncing all post_type contents, always.

Maybe it's a heavy process, isn't it ? @herewithme @asadowski10

**Comment by herewithme** [comment]
It's extremely difficult to know if there have been any changes, especially due to third-party plugins. @MaximeCulea

**Comment by MaximeCulea** [comment]
Get the current menu order and check if it needs to be updated, before saving the post which will trigger the CSF hook.
