### ISSUE TITLE
Useless code and func ?

### ISSUE THREAD

**Issue by MaximeCulea** [BeAPI/bea-content-sync-fusion#11]
https://github.com/BeAPI/bea-content-sync-fusion/blob/537a43b3f7e40edd01f56474ecee0453f5cb9672/bea-content-sync-fusion.php#L85

https://github.com/BeAPI/bea-content-sync-fusion/blob/537a43b3f7e40edd01f56474ecee0453f5cb9672/classes/plugin.php#L149

**Comment by herewithme** [comment]
Yes ! Unless...

**Comment by MaximeCulea** [comment]
*useless 😛
