### ISSUE TITLE
Import / export config

### ISSUE THREAD

**Issue by asadowski10** [BeAPI/bea-content-sync-fusion#12]
Add un option page to import / export network configuration.

**Comment by MaximeCulea** [comment]
https://wordpress.org/plugins/wp-cfm/ could do the trick ?

**Comment by asadowski10** [comment]
yes it can but i prefer no dependencies with other plugins like ACF, SearchWP, FacetWP ...

**Comment by herewithme** [comment]
Related : https://github.com/BeAPI/bea-content-sync-fusion/issues/13

**Comment by herewithme** [comment]
@asadowski10 not wanted, the declaration of connections can and must be done programmatically via PHP and the API :)

See : https://github.com/BeAPI/bea-content-sync-fusion/wiki/Synchronizations-API
