### ISSUE TITLE
Move p2p class into addon folder

### ISSUE THREAD

**Issue by MaximeCulea** [BeAPI/bea-content-sync-fusion#15]

**Comment by MaximeCulea** [comment]
@herewithme @asadowski10 everything is now gathered into `addons/p2p.php`.
Just wondering about : 
- unused code ? https://github.com/BeAPI/bea-content-sync-fusion/blob/bb9d7ee05b309fa63f2f29b79f3695ee1bdbe29c/classes/addons/p2p.php#L44
- multiple hooks :  https://github.com/BeAPI/bea-content-sync-fusion/blob/master/classes/client.php#L261
Any inputs about theses plz ?

**Comment by herewithme** [comment]
IRL ?
