### ISSUE TITLE
Cron de la synchro

### ISSUE THREAD

**Issue by Rahe** [BeAPI/bea-content-sync-fusion#23]
Pour le cron chaque site devrait récupérer le contenu qui lui est destiné.

Cela permettra de supporter le cas :

- Site 1 n'a pas polylang
- Site 2 a polylang 
- Site 1 pousse du contenu vers Site 2

Dans le cas actuel avec l'addon polylang ça ne fonctionne pas car polylang n'est pas installé sur le Site 1 et donc la fonction n'existe pas.

**Comment by herewithme** [comment]
Implémenté dans la version "WP-CLI". @Rahe

**Comment by herewithme** [comment]
Je ferme.
