### ISSUE TITLE
Store media in one folder vs blog's upload dir as option

### ISSUE THREAD

**Issue by MaximeCulea** [BeAPI/bea-content-sync-fusion#24]
https://github.com/BeAPI/bea-content-sync-fusion/blob/master/classes/multisite.php#L11 is forcing one media folder for all sites 💩 
But it should rather be an option + hook to define the way to store media.
See all cases and how to implement both ways :  https://github.com/BeAPI/bea-ms-files-rewriting/blob/master/bea-ms-files-rewriting.php

While we do it, there is a workaround to use for using blog's upload dir : 
<code>add_filter( 'site_option_' . 'ms_files_rewriting', '__return_false', 20 );</code>

**Comment by herewithme** [comment]
This is the only method that scales for a shared media library. An option why not, but let's say that it is not possible to activate the parameter during the lifetime of the project, without manual action of folder migration.

**Comment by Rahe** [comment]
We cannot delete any site after that, good to know.

**Comment by herewithme** [comment]
Why ?

**Comment by Rahe** [comment]
Upload_path empty and rewrite_ms_true check in wp_delete_blog()

**Comment by MaximeCulea** [comment]
```
// Fix folder rewrite, but no site delete
add_filter( 'pre_option_' . 'upload_path', '__return_empty_string' );
add_filter( 'blog_option_' . 'upload_path', '__return_empty_string' );
```

**Comment by MaximeCulea** [comment]
As we discussed, the plugin structure is changing (#33), then this issue is no longer available, right @Rahe ?

**Comment by herewithme** [comment]
Indeed, we can close this issue.
