### ISSUE TITLE
Add possibility to emit to certains lang sites

### ISSUE THREAD

**Issue by MaximeCulea** [BeAPI/bea-content-sync-fusion#27]
If I have a central site, I write contents but would like to emit to only english' sites of the network. Same principle for all languages.

**Comment by MaximeCulea** [comment]
What do you thing about this @BeAPI/content-sync-fusion ?

**Comment by herewithme** [comment]
Does your central site allow you to write in multiple languages?

**Comment by MaximeCulea** [comment]
I have MLP installed on others sites, but no lang plugins on the central one. Let's talk IRL ?
