### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by MaximeCulea** [BeAPI/bea-content-sync-fusion#3]
Improve the readme with :
- [ ] description
- [ ] add installation block
- [ ] reformat the changelog
- [ ] compatibily 
- [ ] how to use
- [ ] home to use : configuration for [taxonomies](https://github.com/BeAPI/bea-content-sync-fusion/issues/61) 
- [ ] add screenshots
- [ ] refactor repository (title, description, tags)
- [ ] crons
- [ ] license
- [ ] github banner
- [ ] github [templates](https://github.com/BeAPI/bea-find-media/tree/master/.github)

**Comment by MaximeCulea** [comment]
Also write the [wiki page](https://github.com/BeAPI/bea-content-sync-fusion/wiki).

**Comment by wpchannel** [comment]
Hello (suite Slack), +1 pour spécifier des infos sur le CRON. :)
