### ISSUE TITLE
Médiathèque Multisite

### ISSUE THREAD

**Issue by Rahe** [BeAPI/bea-content-sync-fusion#33]
Plusieurs cas se présentent à nous en mode multisite + médiathèque :

1. Médiathèque normale, chaque site a sa librairie, le processus copie les médias et fichiers entre les dossiers des sites. Ca fonctionne bien car fichiers et médias sont dans chaque site. Avantage on peut extraire un blog de la plateforme sans problème ou le supprimer de la plateforme.
2. Médiathèque centrale au dossier unique, le site racine est considéré comme central. Les médias uploadés sur les autres sites de la plateforme sont positionnés dans les dossiers du site 1. Avantage on a qu'un seul dossier pour tout et pas de transferts à faire ou de doublons, inconvénients : on ne peut pas extraire ou supprimer un site sans que toute la bibliothèque soit vidée.
3. Médiathèque centrale au dossier unique et dossier par site. On a une médiathèque générale qui pousse vers les sites "enfants" les différents contenus, non supprimables stockés sur le site racine. Le site courant écrit ses propres médias. Les contenus synchros sur les sites enfants remplacent les URLS vers les médias à la volée pour être ceux du site source. Les médias ne sont pas supprimables.

Dans tous les cas en supprimant un fichier sur le site source utilisé en local on perd le fichier.
Voyez-vous d'autres cas ?

**Comment by Rahe** [comment]
Alors ce qui a été choisi est la solution 3.
Chaque site a son dossier et il est possible de synchroniser les médias entre sites.
Les URLS et chemins des fichiers synchronisés sont modifiés à la volée pour être ceux du site distant.

Les plugins que nous devons supporter 
- ACF
- WPThumb
- Optimus
- Miniatures
- Crop d'images
- Watermark
- Media Replacement

**Comment by herewithme** [comment]
@Rahe tu peux nous proposer un PR de ton implémentation ?

**Comment by herewithme** [comment]
Fixed in version 3.2.x
