### ISSUE TITLE
Dashicon monochrome

### ISSUE THREAD

**Issue by wpchannel** [BeAPI/bea-content-sync-fusion#35]
Un joli icône monochrome pour être WordPress friendly? :)

**Comment by MaximeCulea** [comment]
Merci @wpchannel pour ton feedback.

**Comment by herewithme** [comment]
@wpchannel @MaximeCulea done ! https://github.com/BeAPI/bea-content-sync-fusion/commit/24633c8919ab6b2fc116834fe24d5e5dfe7b9367
