### ISSUE TITLE
Associate at site creation

### ISSUE THREAD

**Issue by Rahe** [BeAPI/bea-content-sync-fusion#36]
Add the possibility to choose the synchronisation where to add the site we are about to create.

**Comment by MaximeCulea** [comment]
The idea here is to gather sites into a "site category" ?

**Comment by MaximeCulea** [comment]
Very related to #9 ? @Rahe

**Comment by MaximeCulea** [comment]
Related to https://github.com/BeAPI/bea-content-sync-fusion/issues/9
