### ISSUE TITLE
Table unique key size

### ISSUE THREAD

**Issue by Rahe** [BeAPI/bea-content-sync-fusion#37]
The table unique key size is too big, resulting error :

```CREATE TABLE wp_bea_csf_relations ( `id` INT(20) NOT NULL AUTO_INCREMENT , `type` VARCHAR(255) NOT NULL , `emitter_blog_id` INT(20) NOT NULL , `emitter_id` INT(20) NOT NULL , `receiver_blog_id` INT(20) NOT NULL , `receiver_id` INT(20) NOT NULL , `custom_flag` BOOLEAN NOT NULL , `custom_fields` TEXT NOT NULL, PRIMARY KEY (id), UNIQUE KEY `type_emitter_receiver` (`type`(255), `emitter_blog_id`, `emitter_id`, `receiver_blog_id`, `receiver_id`) );
ERROR 1071 (42000): Specified key was too long; max key length is 767 bytes```

InnoDB engine accepts 767 bytes and MyISAM 1000bytes, we are on utf8mb4 we only will have 191 bytes available.

**Comment by Rahe** [comment]
Same error with the other tables, too long.

**Comment by herewithme** [comment]
https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes

`INNODB utf8 VARCHAR(255)
INNODB utf8mb4 VARCHAR(191)`

**Comment by herewithme** [comment]
See https://github.com/BeAPI/bea-content-sync-fusion/pull/38/

**Comment by Rahe** [comment]
Great !
