### ISSUE TITLE
Add filter before hooks / do action after hook 

### ISSUE THREAD

**Issue by asadowski10** [BeAPI/bea-content-sync-fusion#41]
Add some hooks for The Event Calendar force sync events with tickets

**Comment by asadowski10** [comment]
Problème actuel : 

- J'ajoute un evènement sans le publier
- Je viens ajouter un ticket à cet évènement > action AJAX d'ajout > ajout dans la queue
- Je publie l'event > ajout dans la queue
- Synchronisation : lors de l'insertion du ticket je n'ai pas l'ID de l'évènement.
( l'ID de l'event est stocké seulement en meta du ticket ).

Solution envisagée : 
- Bloquer la synchro auto des tickets
- Au publish_post > ajouter à la queue après l'event les tickets
- Add on ticket pour pour remplacer ensuite l'ID des events dans les méta des tickets

**Comment by herewithme** [comment]
Closed for #52
