### ISSUE TITLE
Content restriction on files

### ISSUE THREAD

**Issue by MaximeCulea** [BeAPI/bea-content-sync-fusion#5]
It seems that the content restriction doesn't work on files.

There are several cases to handle :

- [ ] files archive admin page
- [ ] file single admin page
- [x] file single admin popup
- [x] file library window : don't make selectable items

**Comment by herewithme** [comment]
Fixed into : https://github.com/BeAPI/bea-content-sync-fusion/commit/915897e834c08496dfd4ca68a60d1857368085e4

**Comment by MaximeCulea** [comment]
Do all the above conditions match this change ? 🤔

**Comment by herewithme** [comment]
I think so.

**Comment by MaximeCulea** [comment]
1. files archive admin page
- As list view, it's impossible to preview the file details. Maybe it could be possible to allow the "edit file" link to see into file single admin page, but with all the fields restricted ? ❌ 
- As grid view, it's possible to reach the "file single admin popup", so we can view more info. ✅ 

2. file single admin page
It's not reacheable, see *1* for maybe an enhancement. ❌ 

3. file single admin popup ✅ 
It's possible to see the media details through the admin single popup. No modifications possible.

4. file library window : don't make selectable items
- List view, files are not selected and deleted ✅ 
- File library popup / window, fiels are not deletable ✅ 

So with the cross ones, could you please give your opinion ? 🤗

**Comment by herewithme** [comment]
@MaximeCulea Good idea, but it's not a priority in the backlog!
