### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by MaximeCulea** [BeAPI/bea-content-sync-fusion#6]
1. Replace textdomain's constant with textdomain's string into gettext functions
2. Add po / mo for main languages

**Comment by herewithme** [comment]
Fix into this commit: 
https://github.com/BeAPI/bea-content-sync-fusion/commit/5fccb85d3cca63087a55e87359cbd94f3f1f0a7d

**Comment by MaximeCulea** [comment]
👍
