### ISSUE TITLE
Notice on "Edit" page

### ISSUE THREAD

**Issue by chrishrmnn** [BeAPI/bea-content-sync-fusion#62]
Si WP_DEBUG est activé, deux "Notice" sur la page "Edit".

![Notices](https://user-images.githubusercontent.com/5339141/33830596-17ec9984-de75-11e7-8527-e4844bf26c12.png)

**Comment by MaximeCulea** [comment]
@BeAPI/content-sync-fusion is this a known issue ? I have something about it, but not sure.
Thx for your feedback.

**Comment by herewithme** [comment]
Fixed : https://github.com/BeAPI/bea-content-sync-fusion/commit/6ca536e33e8de10277c807994af27525ffd37e94

**Comment by herewithme** [comment]
Thanks !
