### ISSUE TITLE
When manual sync, contents are not added automatically to queue

### ISSUE THREAD

**Issue by MaximeCulea** [BeAPI/bea-content-sync-fusion#63]
For now, there is an automatic and manual mode.
But what if I would like to push a content automatically when I publish it, but choose where to send it ?

I am thinking about a third type of sync, which is in "automatic" mode but with none receivers. They will be manually chosen from content's meta box.

Is it possible ?
What do you think about this ?

**Comment by MaximeCulea** [comment]
@BeAPI/content-sync-fusion your feedback worth it ? thx

**Comment by asadowski10** [comment]
@MaximeCulea 

You are describing the manual mode there. In the manual mode, you can come and select the site (s) where you want to send your content.

On save_post, it feeds the synchronization queue. The CRON comes to synchronize the elements.

2 tracks of errors:
- Incorrect plugin configuration
- Error introduced between the stable version and the new commits on master.

Thanks,

**Comment by herewithme** [comment]
Possible to have more precision? A screenshot of the synchronization concerned?

**Comment by MaximeCulea** [comment]
Maybe @chrishrmnn could provide a screenshot of his case ? 🤗

**Comment by chrishrmnn** [comment]
When I publish my article with an automatic synchronization:
![capture d ecran 2017-12-11 a 16 53 46](https://user-images.githubusercontent.com/5339141/33841065-f09aadc2-de96-11e7-8949-1eddc66eaedf.png)

The element goes to task list and is not automatically published on the others sites
![capture d ecran 2017-12-11 a 17 10 05](https://user-images.githubusercontent.com/5339141/33841124-1aeb699a-de97-11e7-9cc6-6c2d5de0372d.png)


**Expectation**:
Automatic synchronization will publish on "save_post" on the other(s) site(s) but with the possibility of choosing which site in the box, like:
![capture d ecran 2017-12-11 a 17 20 56](https://user-images.githubusercontent.com/5339141/33841338-bee9a7e6-de97-11e7-9e17-5e0824f4a037.png)
