### ISSUE TITLE
Support for WP Media Library

### ISSUE THREAD

**Issue by MaximeCulea** [BeAPI/bea-content-sync-fusion#65]
WP : 4.8.3
Content Sync Fusion : 3.0.7 ( also tested with trunk one)
WP Media Library : 4.2.7

When using [WP Media Library](https://www.joomunited.com/wordpress-products/wp-media-folder), the created folders on a main site are not duplicated to the synced sites. With luck the media are.

**Comment by herewithme** [comment]
To be compatible with this plugin.
You have to create / edit the media sync and add the taxonomy of this plugin.
Moreover, the 3.4.0 version fixes adding media to a folder by dragging and dropping.
