### ISSUE TITLE
"All, except emitters"

### ISSUE THREAD

**Issue by MaximeCulea** [BeAPI/bea-content-sync-fusion#66]
![image](https://user-images.githubusercontent.com/5576409/36689399-8e352970-1b2f-11e8-8fbf-946fca66b424.png)
When choosing the receivers, "All, except emitters" it generates a fatal.
Same, it can't save the value when editing the sync.

**Comment by herewithme** [comment]
Fixed : https://github.com/BeAPI/bea-content-sync-fusion/commit/c1b9e7bded44bd1e871e4d2f7bf4a76410810989

**Comment by MaximeCulea** [comment]
👍
