### ISSUE TITLE
Plugin name

### ISSUE THREAD

**Issue by MaximeCulea** [BeAPI/bea-content-sync-fusion#67]
- the repository is called bea-content-sync-fusion
- the plugin name into readme is BEA Content Sync Fusion
- the plugin name into WordPress head is BEA - Content Synchronization - Fusion

I propose, in order to standardize, to rename it into *BEA - Content Sync Fusion*.

@BeAPI/content-sync-fusion what do you think about this ?

**Comment by herewithme** [comment]
Works for me.

**Comment by asadowski10** [comment]
Top 👍

**Comment by herewithme** [comment]
Updated!
