### ISSUE TITLE
The Event Calendar synchronisation

### ISSUE THREAD

**Issue by asadowski10** [BeAPI/bea-content-sync-fusion#69]
Lors de la création d'un evenement "normal" c'est à dire sans 'récurrence', lorsque celui-ci est synchronisé la meta "_EventRecurrence" est ajoutée et donc l'event devient récurent.

Sur les billets du coup j'ai cette erreur : "This is a recurring event. If you add tickets they will only show up on the next upcoming event in the recurrence pattern. The same ticket form will appear across all events in the series. Please configure your events accordingly."

**Comment by herewithme** [comment]
C'est corrigé dans la dernière version du plugin.
J'ai backporté le correctif dans la branche 3.0.7.x de ton projet
https://github.com/BeAPI/bea-content-sync-fusion/compare/3.0.7...3.0.7.1
