### ISSUE TITLE
autosync not running but posts are queued

### ISSUE THREAD

**Issue by fine-G** [BeAPI/bea-content-sync-fusion#77]
I tried to use content sync fusion in mode auto but it doesn’t work. What must I do to proceed the queue? 

I publish a post (from CPT), the post is in the queue, an on the receiver site on the dashboard.
I can add the post form the dashboard to the receiver site. Works perfect. 
But not automatically.

Can you help me?

**Comment by MaximeCulea** [comment]
Hi @fine-G,

Thx you reaching us out.

You mean that proceeding manually the queue is perfectly working, which is not the case in automatic mode with same settings ?

Thank you

**Comment by herewithme** [comment]
Have you set up a CRON job on your server? @fine-G ?

**Comment by fine-G** [comment]
> Have you set up a CRON job on your server? @fine-G ?

No, what I have to do to run a cron job for the plugin?

**Comment by fine-G** [comment]
> Hi @fine-G,
> 
> Thank you reaching us out.
> 
> You mean that proceeding manually the queue is perfectly working, which is not the case in automatic mode with same settings ?

Yes, manual is perfect, auto not

**Comment by fine-G** [comment]
> Please have a look to the documentation here : https://github.com/BeAPI/bea-content-sync-fusion/wiki/CRON-Jobs
> 
> Let us know.

a bit lost what have I to do with this code?

**Comment by fine-G** [comment]
> > Please have a look to the documentation here : https://github.com/BeAPI/bea-content-sync-fusion/wiki/CRON-Jobs
> > Let us know.
> 
> a bit lost what have I to do with this code?

I

> Please have a look to the documentation here : https://github.com/BeAPI/bea-content-sync-fusion/wiki/CRON-Jobs
> 
> Let us know.

I have installed the WP Crontrol Plugin but  I habe no idea, how I can run the cron job:
I need a hook when I will use the arguments. What is the hook for this?
Or I can add a php function, but what is the code?

**Comment by herewithme** [comment]
In fact, this plugin can not work with WordPress CRON tasks. (aka WP-CRON)
You must configure CRONs on your dedicated server, for example.

More explanation here: https://en.wikipedia.org/wiki/Cron

**Comment by fine-G** [comment]
> In fact, this plugin can not work with WordPress CRON tasks. (aka WP-CRON)
> You must configure CRONs on your dedicated server, for example.
> 
> More explanation here: https://en.wikipedia.org/wiki/Cron

Thanks then I have to ask an other developer/admin to do this
