### ISSUE TITLE
Sync Taxonomies: ACF Taxonomy Field and BAE Sync  returns server error 500

### ISSUE THREAD

**Issue by fine-G** [BeAPI/bea-content-sync-fusion#78]
When I activate the "Save Terms" Option (Connect selected terms to the post) in the ACF taxonomy field with active BAE Sync Plugin, the Post will save the values/changes but end up in an error 500 from the post.php (white page)

**Comment by herewithme** [comment]
@fine-G Can you activate WP debug mode to give us the error message?

**Comment by fine-G** [comment]
> @fine-G Can you activate WP debug mode to give us the error message?

a memory problem, but is this true? the post has 20 fields, not much:
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 69632 bytes) in /var/www/wp-homepage/wp-includes/functions.php on line 5170

the server has a memory limit of 256mb

**Comment by fine-G** [comment]
Hello Amaury, 
today I was back on this job… I plushed up the server memory limit to 32000M and i doesn’t help.
did you see any change to get the sync with taxonomies (in post an acf field !) to run?

Here from the log:
[18-Dec-2018 16:18:17 UTC] PHP Fatal error:  Out of memory (allocated 1413480448) (tried to allocate 20480 bytes) in /var/www/xxxxxxxx/wp-content/plugins/query-monitor/classes/Backtrace.php on line 92

**Comment by herewithme** [comment]
@fine-G sorry for the delay (holidays...)

Try to deactivate the plugin "query-monitor" and try again :)

**Comment by herewithme** [comment]
No news, i close.
