### ISSUE TITLE
Create a WP-CLI command for all resync possibilities

### ISSUE THREAD

**Issue by herewithme** [BeAPI/bea-content-sync-fusion#8]

**Comment by herewithme** [comment]
@asadowski10 @MaximeCulea do you agree with the following implementation ?

- [ ] wp content-sync-fusion exec-queue --alternativeq="false|true"
- [ ] wp content-sync-fusion flush-all
- [ ] wp content-sync-fusion resync --all-network="false|true" --attachments --posttype="any" --taxonomies="any"

**Comment by asadowski10** [comment]
On wp content-sync-fusion exec-queue --alternativeq="false|true", this to execute all ? or 500 by 500 ? --quantity="all|500" ?

**Comment by herewithme** [comment]
@asadowski10 I do not recommend "all" because it's not really optimized for. On the other hand, the smart guys will still be able to set a very large number. Moreover the name of the variable is more "limit" than "quantity";)

**Comment by herewithme** [comment]
Implemented in 3.2 version.
