### ISSUE TITLE
On site creation, check connections to force sync

### ISSUE THREAD

**Issue by MaximeCulea** [BeAPI/bea-content-sync-fusion#9]

**Comment by herewithme** [comment]
@MaximeCulea Is that already the case?

**Comment by MaximeCulea** [comment]
[no](https://github.com/BeAPI/bea-content-sync-fusion/blob/master/classes/multisite.php#L32) ! 😛

**Comment by MaximeCulea** [comment]
[Inspiration]"https://github.com/BeAPI/bea-content-sync-fusion/blob/c10651ebe0a0b6967d3f8c516508fc12d151634e/classes/models/synchronization.php#L253"

**Comment by MaximeCulea** [comment]
@herewithme Should be implemented for the MS Intersport Montagne.

**Comment by herewithme** [comment]
Implemented on https://github.com/BeAPI/bea-content-sync-fusion/commit/67ade75f006aa8d9753336d67e6de5a5a77b4d4b
